In [2]:
#1. Import the numpy package under the name np

import numpy as np

In [11]:
#2. Print the numpy version and the configuration
print np.__version__

1.13.3


In [15]:
#3. Create a null vector of size 10
Z=np.zeros(10)
print Z

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [17]:
#4. How to get the documentation of the numpy add function from the command line?

print np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [19]:
#5. 
Z = np.zeros(10)
Z[4] = 1
print Z

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [21]:
#6. Create a vector with values ranging from 10 to 49
print np.arange(10,50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
#7. Reverse a vector (first element becomes last) 
Z = np.arange(1,11)
X = np.flipud(Z)
print X

Y = Z[::-1]
print Y
Z[5] = 11
print Z
print Y
print X


[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5 11  7  8  9 10]
[10  9  8  7 11  5  4  3  2  1]
[10  9  8  7 11  5  4  3  2  1]


In [33]:
#8. Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(1,10).reshape(3,3)
print Z

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
#9. Find indices of non-zero elements from [1,2,0,0,4,0] 
print np.info(np.nonzero)
np.nonzero([1,2,0,0,4,0])

 nonzero(a)

Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order. The corresponding non-zero
values can be obtained with::

    a[nonzero(a)]

To group the indices by element, rather than dimension, use::

    transpose(nonzero(a))

The result of this is always a 2-D array, with a row for
each non-zero element.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Examples
--------
>>> x = np.array([[1,0,0], [0,2,0], [1,1,0]])
>>> x
array([[1, 0, 0],
       

(array([0, 1, 4]),)

In [57]:
#10. Create a 3x3 identity matrix
Z = np.eye(3,3,0)
print Z

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [59]:
#11. Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print Z

[[[ 0.41933967  0.33926864  0.61500713]
  [ 0.22935983  0.19403242  0.06815862]
  [ 0.24443106  0.83765153  0.90739313]]

 [[ 0.73050686  0.6575582   0.69478517]
  [ 0.36702566  0.08745719  0.06728119]
  [ 0.97175405  0.28921286  0.39990596]]

 [[ 0.73286488  0.9920209   0.69332136]
  [ 0.84846414  0.36210624  0.20027954]
  [ 0.15309241  0.27893518  0.9345395 ]]]


In [65]:
#12. Create a 10x10 array with random values and find the minimum and maximum values 
np.random.random((10,10))
Zmin, Zmax = np.min(Z),np.max(Z)
print Zmin, Zmax

0.0672811891077 0.992020902089


In [70]:
#13.Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
Zmean = np.mean(Z,0)
print Zmean

0.448674703737


In [86]:
#14. Create a 2d array with 1 on the border and 0 inside
n = 4
Z = np.zeros((n,n))
Z[0,:] = 1
Z[:,0] = 1
Z[n-1,:] = 1
Z[:,n-1] = 1
print Z


Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

print Z

[[ 1.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [95]:
#15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [96]:
#16. Create a 8x8 matrix and fill it with a checkerboard pattern



In [99]:
#18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [109]:
#19. Create a checkerboard 8x8 matrix using the tile function
print np.tile( np.array([[0,1],[1,0]]), (4,4))

# Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
# print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [113]:
#20. Normalize a 5x5 random matrix
Z = np.random.random(25).reshape(5,5)
print Z
Zmin, Zmax = Z.min(),Z.max()
Znor = Z-Zmin/(Zmax-Zmin)
print "normalizing..."
print Znor

[[ 0.85629843  0.07405228  0.25198832  0.83144153  0.3245175 ]
 [ 0.31754074  0.30284539  0.95283346  0.32795587  0.95970429]
 [ 0.13175334  0.72942365  0.59906785  0.8681869   0.43394554]
 [ 0.19632275  0.29932956  0.66569248  0.43758938  0.32773303]
 [ 0.83750631  0.17157327  0.50217863  0.7427954   0.04581959]]
normalizing...
[[ 0.80616127  0.02391512  0.20185116  0.78130436  0.27438033]
 [ 0.26740357  0.25270823  0.9026963   0.27781871  0.90956712]
 [ 0.08161618  0.67928649  0.54893069  0.81804974  0.38380837]
 [ 0.14618558  0.2491924   0.61555532  0.38745221  0.27759587]
 [ 0.78736915  0.1214361   0.45204147  0.69265823 -0.00431758]]


In [116]:
#21. Create a custom dtype that describes a color as four unisgned bytes (RGBA)

color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])
print color

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [118]:
#22. Multiply a 5x3 matrix by a 3x2 matrix 
X = np.arange(15).reshape(5,3)
Y = np.arange(6).reshape(3,2)

np.dot(X,Y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [122]:
#23. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 <= Z)& (Z<=8)] *= -1

print Z

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [123]:
#24. 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10
